import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BeakerIcon } from "@heroicons/react/solid";
import Footer from "../components/Footer";
import Header from "../components/Header";
//import { activities } from "../data";
import ActivityCard from "../components/ActivityCard";
import { useEffect, useState } from "react";

export default function Home() {
  const [filter, setFilter] = useState("inbox");
  const [calls, setCalls] = useState([]);
  const [refresh, setRefresh] = useState(true)

 console.log({calls, refresh})

  useEffect(() => {
    fetch("https://aircall-job.herokuapp.com/activities")
      .then((res) => res.json())
      .then((data) => setCalls(data))
      .catch((error) => console.error(error));
  }, []);

  useEffect(() => {

    fetch("https://aircall-job.herokuapp.com/activities")
      .then((res) => res.json())
      .then((data) => {
        let newList
        if (filter === "archive") {
          newList = data.filter((call) => call.is_archived);
        } else if (filter === "inbox") {
          newList = data.filter((call) => !call.is_archived);
        } else {
          newList = data;
        }
        setCalls(newList)
      
      
      })
      .catch((error) => console.error(error));

    

  }, [filter, refresh]);


  return (
    <div className="bg-gray-700 flex items-center justify-center h-screen relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-[666px] w-[376px] border rounded-md bg-white relative overflow-y-auto">
        <Header setFilter={setFilter} />

        <main className=" ">
          {calls.map((activity) => (
            <ActivityCard key={activity.id} activity={activity} refresh={refresh} setRefresh={setRefresh} />
          ))}
        </main>

        {/* Main */}

        <Footer />
      </div>
    </div>
  );
}
