import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BeakerIcon } from "@heroicons/react/solid";
import Footer from '../components/Footer';
import Header from '../components/Header';
import {activities} from "../data"
import ActivityCard from '../components/ActivityCard';

export default function Home() {



  return (
    <div className="bg-gray-700 flex items-center justify-center h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-[666px] w-[376px] border rounded-md bg-white relative overflow-y-auto">
        <Header />

        <main className=" ">
          {activities.map((activity) => (
            <ActivityCard key={activity.id} activity={activity} />
          ))}
        </main>

        {/* Main */}

        <Footer />
      </div>
    </div>
  );
}
